using EulerLibrary.Helpers;
using System.Linq;

namespace EulerLibrary
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Problem2
    {
        public FibonacciGenerator fibonacciGenerator;
        public int Sum;

        public Problem2()
        {
            fibonacciGenerator = new FibonacciGenerator(0, 4000000);
            Run();
        }

        private void Run()
        {
            var evenList = fibonacciGenerator
                .FibonacciList
                .Where(x => x % 2 == 0);
            Sum = evenList.Sum();
        }
    }
}